// Rich Synonym & Keyword Dictionary for Natural Language Stock Finding
export const CLIENT_KEYWORD_MAP: Record<string, string[]> = {
  "maggi": ["NESTLEIND"],
  "maggie": ["NESTLEIND"],
  "noodles": ["NESTLEIND"],
  "kitkat": ["NESTLEIND"],
  "coffee": ["NESTLEIND", "DEVYANI", "TATACONSUM"],
  "nescafe": ["NESTLEIND"],
  "chocolate": ["NESTLEIND"],
  "bullet": ["EICHERMOT"],
  "classic 350": ["EICHERMOT"],
  "royal enfield": ["EICHERMOT"],
  "hunter": ["EICHERMOT"],
  "himalayan": ["EICHERMOT"],
  "thar": ["M&M"],
  "scorpio": ["M&M"],
  "xuv": ["M&M"],
  "bolero": ["M&M"],
  "tractor": ["M&M"],
  "nexon": ["TATAMOTORS"],
  "harrier": ["TATAMOTORS"],
  "safari": ["TATAMOTORS"],
  "punch": ["TATAMOTORS"],
  "curvv": ["TATAMOTORS"],
  "jio": ["RELIANCE"],
  "petrol": ["RELIANCE", "IOC", "BPCL", "ONGC"],
  "diesel": ["RELIANCE", "IOC", "BPCL", "ONGC"],
  "oil": ["ONGC", "OIL", "RELIANCE", "IOC", "BPCL"],
  "refinery": ["RELIANCE", "IOC", "BPCL"],
  "ambani": ["RELIANCE"],
  "airtel": ["BHARTIARTL"],
  "5g": ["BHARTIARTL", "RELIANCE"],
  "sim": ["BHARTIARTL", "RELIANCE"],
  "broadband": ["BHARTIARTL", "RELIANCE"],
  "blinkit": ["ZOMATO"],
  "zomato": ["ZOMATO"],
  "food delivery": ["ZOMATO", "SWIGGY", "JUBLFOOD", "DEVYANI"],
  "swiggy": ["SWIGGY"],
  "instamart": ["SWIGGY"],
  "zudio": ["TRENT"],
  "westside": ["TRENT"],
  "star bazaar": ["TRENT"],
  "apparel": ["TRENT", "PAGEIND", "VEDANT", "BATAINDIA"],
  "fashion": ["TRENT", "NYKAA", "PAGEIND", "TITAN"],
  "dominos": ["JUBLFOOD"],
  "domino's": ["JUBLFOOD"],
  "pizza": ["JUBLFOOD", "DEVYANI"],
  "kfc": ["DEVYANI"],
  "pizza hut": ["DEVYANI"],
  "costa coffee": ["DEVYANI"],
  "train": ["RVNL", "IRFC", "IRCTC", "RAILTEL", "CONCOR"],
  "trains": ["RVNL", "IRFC", "IRCTC", "RAILTEL", "CONCOR"],
  "railway": ["RVNL", "IRFC", "IRCTC", "RAILTEL", "CONCOR"],
  "railways": ["RVNL", "IRFC", "IRCTC", "RAILTEL", "CONCOR"],
  "vande bharat": ["RVNL", "IRFC", "IRCTC"],
  "ticket": ["IRCTC"],
  "food in train": ["IRCTC"],
  "tejas": ["HAL"],
  "fighter jet": ["HAL"],
  "defence": ["HAL", "BEL", "MAZDOCK", "BDL", "COCHINSHIP", "SOLARINDS"],
  "defense": ["HAL", "BEL", "MAZDOCK", "BDL", "COCHINSHIP", "SOLARINDS"],
  "missile": ["BDL", "BEL", "HAL"],
  "warship": ["MAZDOCK", "COCHINSHIP", "GRSE"],
  "submarine": ["MAZDOCK"],
  "solar": ["IREDA", "TATACOMM", "NTPC"],
  "green energy": ["IREDA", "NTPC", "TATAPOWER"],
  "ev": ["TATAMOTORS", "M&M", "OLAELEC", "OLECTRA", "AMARAJABAT", "EXIDEIND"],
  "electric vehicle": ["TATAMOTORS", "M&M", "OLAELEC", "OLECTRA"],
  "battery": ["AMARAJABAT", "EXIDEIND"],
  "it": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "LTIM", "TATAELXSI"],
  "software": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "LTIM"],
  "bank": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", "BANKBARODA", "PNB"],
  "banking": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", "BANKBARODA", "PNB"],
  "loan": ["HDFCBANK", "SBIN", "BAJFINANCE", "BAJAJFINSV"],
  "credit card": ["HDFCBANK", "SBIN", "ICICIBANK", "AXISBANK"],
  "fmcg": ["ITC", "HINDUNILVR", "NESTLEIND", "BRITANNIA", "TATACONSUM", "DABUR", "MARICO", "COLPAL"],
  "soap": ["HINDUNILVR", "GODREJCP"],
  "shampoo": ["HINDUNILVR", "DABUR"],
  "toothpaste": ["COLPAL", "DABUR"],
  "biscuit": ["BRITANNIA", "PARLE"],
  "cigarette": ["ITC"],
  "hotel": ["ITC", "INDHOTEL", "EIHOTEL"],
  "hospital": ["APOLLOHOSP", "MAXHEALTH", "FORTIS"],
  "medicine": ["SUNPHARMA", "CIPLA", "DRREDDY", "DIVISLAB", "MANKIND"],
  "pharma": ["SUNPHARMA", "CIPLA", "DRREDDY", "DIVISLAB", "MANKIND"],
  "cement": ["ULTRACEMCO", "AMBUJACEM", "ACC", "SHREECEM"],
  "steel": ["TATASTEEL", "JSWSTEEL", "JINDALSTEL", "SAIL"],
  "gold": ["TITAN", "KALYANKJIL", "MUTHOOTFIN", "MANAPPURAM"],
  "jewellery": ["TITAN", "KALYANKJIL"],
  "paint": ["ASIANPAINT", "BERGEPAINT", "KANSAINER"],
  "asian paints": ["ASIANPAINT"],
  "footwear": ["BATAINDIA", "RELAXO", "CAMPUS", "METROBRAND"],
  "shoes": ["BATAINDIA", "RELAXO", "CAMPUS", "METROBRAND"],
  "cinema": ["PVRINOX"],
  "movie": ["PVRINOX"],
  "flight": ["INDIGO"],
  "airline": ["INDIGO"],
  "telecom": ["BHARTIARTL", "RELIANCE", "IDEA"],
  "nifty 50": ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "ITC", "BHARTIARTL", "SBIN", "LT", "HINDUNILVR", "TATAMOTORS", "M&M"],
  "nifty": ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "ITC", "BHARTIARTL", "SBIN", "LT", "HINDUNILVR", "TATAMOTORS", "M&M"],
  "nifty 30": ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "ITC", "BHARTIARTL", "SBIN", "LT", "HINDUNILVR", "TATAMOTORS", "M&M"],
  "sensex": ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "ITC", "BHARTIARTL", "SBIN", "LT", "HINDUNILVR", "TATAMOTORS", "M&M"],
  "sensex 30": ["RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "ITC", "BHARTIARTL", "SBIN", "LT", "HINDUNILVR", "TATAMOTORS", "M&M"],
  "nifty it": ["TCS", "INFY", "HCLTECH", "WIPRO", "TECHM", "LTIM", "TATAELXSI", "PERSISTENT", "COFORGE"],
  "nifty bank": ["HDFCBANK", "ICICIBANK", "SBIN", "AXISBANK", "KOTAKBANK", "BANKBARODA", "PNB", "FEDERALBNK"],
  "nifty auto": ["TATAMOTORS", "M&M", "MARUTI", "BAJAJ-AUTO", "EICHERMOT", "HEROMOTOCO", "TVSMOTOR"],
  "nifty pharma": ["SUNPHARMA", "CIPLA", "DRREDDY", "DIVISLAB", "APOLLOHOSP", "MANKIND", "ZYDUSLIFE"],
  "psu": ["SBIN", "HAL", "BEL", "RVNL", "IRFC", "IRCTC", "NTPC", "ONGC", "POWERGRID", "COALINDIA", "SAIL", "IOC", "BPCL", "GAIL", "PFC", "RECLTD", "IREDA"]
};
